### ISSUE TITLE
Only water visible on ver 6.1.3 -- 15apr17 on GNU/LINUX

### ISSUE THREAD

**Issue by Festerdam** [fastrgv/AdaGate#1]
I followed the steps that the readme file told me to do.
`wget https://github.com/fastrgv/AdaGate/releases/download/v6.1.3/ag15apr17.tar.gz`
`tar -xzvf ag15apr.tar.gz`
`mv agate adagate_install_directory`
`cd adagate_install_directory`
`./adagate_gnu`

When the game starts, the first thing that I see is water. I tried to turn around to see if there's anything else, but the game doesn't react to the touch-pad nor the mouse, but I could turn with "A" and "D" keys. There was nothing behind me, just more water and the sky seems to be black(I couldn't look up because there was no key I found that rotated my view up and down.). I swam a bit with "W" and "S" keys and I could hear in some zones water splashing while I was swimming, but in others there was no splashing of water what makes me think that there is land, it is just not displayed, I also sank a bit when I swam in the zones where I could hear the splashing.

The output of `./adagate_gnu` is:

> Please be patient...AdaGate is slow to load...
>
>
>No resume file found
> Puzzle Difficulty =  1
>...no game controller detected...
>We compiled against SDL version  2. 0. 3
>SDL_compiledversion= 2003
>We linked against SDL version  2. 0. 3
>MultSample is NOT supported
>./settings.txt file not found...Using default game controller settings
>Window: wid-X-hit : 1366 X  768
>Drawable: Fwid-X-Fhit :  1366 X  768

**Comment by fastrgv** [comment]
Festerdam:  the first 20 seconds is a spiraling flyover of the island with no user input accepted.  After that a touchpad, mouse, and keyboard should be active.  I don't know what to tell you, except that as a last resort you could a) try it on a friend's MacBook (adagate_osx), or b) get an Ada compiler from AdaLibre and use the script to recompile it yourself on your machine.   The terminal output you sent me all looks normal.  BTW, it runs, but runs poorly on a tiny Intel NUC computer (with embedded Intel graphics) I have.  I notice that multisample is not supported so AdaGate may need a better graphics card.  For the sake of a test, you could download my "RufasGate" app, which is very much older but is less demanding graphically. 

Almost any other of my apps are less graphically demanding, so you might try some of them just for an experiment, too.

Rod

**Comment by fastrgv** [comment]
the first 20 seconds is a spiraling flyover of the island with no user
input accepted. After that a touchpad, mouse, and keyboard should be
active. I don't know what to tell you, except that as a last resort you
could a) try it on a friend's MacBook (adagate_osx), or b) get an Ada
compiler from AdaLibre and use the script to recompile it yourself on your
machine. The terminal output you sent me all looks normal. BTW, it runs,
but runs poorly on a tiny Intel NUC computer (with embedded Intel graphics)
I have. I notice that multisample is not supported so AdaGate may need a
better graphics card. For the sake of a test, you could download my
"RufasGate" app, which is very much older but is less demanding
graphically.

Almost any other of my apps are less graphically demanding, so you might
try some of them just for an experiment, too.

Rod

**Comment by fastrgv** [comment]
Festerdam,  I'm interested in any updated info or conclusions that you care to share!  Rod

**Comment by Festerdam** [comment]
I ran these commands in the agate directory:
`rm adagate_gnu adagate_gnu_d adagate_gnu_ss`
`./lcmpd.sh`
`./adagate_gnu`

lcmpd.sh gave me this output:
>gnatbind -aO/home/sausage/Downloads/agate/obj -I./adabindings/gl -I./adabindings/sdlada -I./adabindings/AdaPngLib -I./adabindings/sfmlAudio -x /home/sausage/Downloads/agate/obj/adagate.ali
>gnatlink /home/sausage/Downloads/agate/obj/adagate.ali -o adagate_gnu_d -O3 -lGL -lz -lstdc++ -Xlinker -rpath=$ORIGIN/libs/gnu -L/home/sausage/Downloads/agate/libs/gnu -lsnd4ada -lSDL2 -lsfml-audio -lsfml-system -lopenal -lcrypto -logg -lvorbis -lvorbisenc -lvorbisfile -lFLAC

There was no difference between the binary files that were present before the compilation and the binary files that appeared after I ran lcmpd.sh. Both of them seem not to display the graphics well.

I tried RufasGate. The differences I noted were the following:

- The game took much less time to load.

- The sky was solid-white colored instead of like in AdaGate solid-black.

- The zone that is supposed to be land is solid-white colored(At least I know at what point ends the island.).

- I can't move forward, but I can turn.

There are only Windows users around me. I only met once someone who was a Mac user, but that person left me after a week, therefore I currently can't test any software on a Mac.

**Comment by fastrgv** [comment]
The good news is that those compiler messages seem normal with no errors.
I don't have suggestions,  only questions...
what graphics card do you have;  is it OpenGL v3.3 capable? (it needs to be).
My personal favorite distro for getting all my hardware working easily is Linux Mint.
My games run Ok even on my least-capable machine, which uses embedded Intel graphics
running Linux Mint.

**Comment by Festerdam** [comment]
The output of `lspci | grep VGA` is:
```
00:02.0 VGA compatible controller: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display (rev 0e)
```

The output of `lshw -C display` is:
```
  *-display               
       description: VGA compatible controller
       product: Atom Processor Z36xxx/Z37xxx Series Graphics & Display
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 0e
       width: 32 bits
       clock: 33MHz
       capabilities: pm msi vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:193 memory:d0000000-d03fffff memory:c0000000-cfffffff ioport:f080(size=8)
```

The output of `glxinfo | grep "OpenGL version string"` is:
```
OpenGL version string: 3.0 Mesa 11.2.0
```

It seems like I have an older version of OpenGL. That explains everything.

**Comment by fastrgv** [comment]
I'm pretty certain that you are correct and that your GPU is too old.
Note that the startup screen on rufasgate_gnu displays the OGL version numbers,
major & minor (if successful).  On my machine it says:

OGL query:  CORE profile
OGL query:  Forward-Compatible bit is set
OGL query: OpenGL major version = 3
OGL query: OpenGL minor version = 3

So I shall now be closing this issue.
