### ISSUE TITLE
Licensing and source

### ISSUE THREAD

**Issue by donaldr3** [fastrgv/AdaGate#2]
You have  a repo hero with a license and some images, with a link to a tarbal. But the tarball doesn't have a license file it appears. Why not put the source in the repo, with the license together?

**Comment by fastrgv** [comment]
donaldr3,

Just to be clear...
Every single *.ads, *.adb source file (Ada), as well as every script (*.sh)
has a complete GPLv3 license statement at its top, with a reference to
http://www.gnu.org/licenses/.

Are you suggesting I include the object of that reference too?

Rod

**Comment by fastrgv** [comment]
...I think that is what you are suggesting.  Since it would be a negligible addition to the tarball size, I guess I shall do that!
