### ISSUE TITLE
general feedback

### ISSUE THREAD

**Issue by ohenley** [fastrgv/AdaGate#3]
Hi,

First, your games looks great! but ...

1) I do not know how you compressed your tar.gz, but it took more than 1 hour to uncompress. This is super un-welcoming for a stranger that want to give a try at your code/game. Bandwidth is cheap these days, maybe compress less and things with be smoother for users. (Uncompress should takes seconds at most) 

2) Why dont you provide code + build instructions? Github is not made for binaries.

3) I will inspect your tar.gz archive, but I might not even execute it if I feel your package may be insecure to me. This is one of the reasons why most people prefer source code on github. We can see what the code will do once executed. 

ok, keep up the good work.

**Comment by fastrgv** [comment]
Hi, I guess you are not using linux or osx.  On Windows I use some utility
I found...I forgot the name but I'll get back to you with the name.
Anyway, after you unzip there is a tar file you must untar (my same utility
does that too).  It takes about 4 seconds.  When you do that you will see
all the source code, build scripts and libraries you need to compile it
yourself.  No need to execute the delivered binaries if you want to build
it yourself.
I'll send you the zip utiltiy name within the hour.  OTOH, you have raised
a good point that I should not expect most windows users to know how to
unzip & untar.  Maybe I'll create a zip file for those users on windows in
the future.

**Comment by fastrgv** [comment]
Use this:
www.7-zip.org

it's called 7zip and the commands you would need are like:
1) 7z ag.tar.gz  (unzips tarball)
2) 7z ag.tar  (untars the tarball)

After step 2, you would see a new directory like .\agate\
that has all the code, scripts, data, resources as well as some prebuilt
executables for those who are gamers rather than developers.


done.

**Comment by ohenley** [comment]
yeah I already use peazip, a front-end for 7zip.

probably my archive is corrupted... relatively bad connection from here. 
I will get it again tomorrow from my job to see.

Thx

**Comment by fastrgv** [comment]
Finally, please read "sourceCode.txt".

**Comment by fastrgv** [comment]
Well...I'm very interested to make sure that you were able to download, unzip, and rebuild AdaGate.
I went to your github repository so I see you are probably an Ada expert, which makes your opinion even more valuable to me.  And, in case you tried running my delivered executable, did it work Ok?
Thx, Rod

**Comment by ohenley** [comment]
Something is off.

I re-downloaded your archive and still after 10 minutes, the uncompress was at 95%. It stucks there.

1. Maybe you are compressing too aggressively?
2. Maybe you are archiving/compressing using advanced options not well supported by all softs.

Try decompressing ag10dec18.tar.gz using peazip on windows. This soft should work. It is used by most folks in the game industry.
Maybe consider *.zip? 

IHMO, it should work flawlessly for everybody so no need to stay on tar.gz if it creates friction.

Give me news. Thx!

**Comment by fastrgv** [comment]
I've already checked it with 7z [www.7-zip.org] to make sure I did not upload a bogus file, and it worked fine.  I did this
7z ag10dec18.tar.gz
7z ag10dec18.tar
then there appeared a new directory .\agate\
My info is that peazip CAN act as a front end for 7z, among many other 3rd party unzip utilities.
So I believe if your having trouble, then your underlying unzip utility is not 7z.
My development machine runs linux mint.  Let me check to see if I can easily create an ordinary zip file.  I'll get back to you later.

**Comment by fastrgv** [comment]
In about 10 minutes you will find "agtar.zip" in the latest release of AdaGate.

**Comment by ohenley** [comment]
Using 7z, command lie, windows 10:

C:\Users\olivier\Downloads>7z e ag10dec18.tar.gz

7-Zip 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30

Scanning the drive for archives:
1 file, 150239420 bytes (144 MiB)

Extracting archive: ag10dec18.tar.gz
--
Path = ag10dec18.tar.gz
Type = gzip
Headers Size = 24

Everything is Ok

Size:       271872000
Compressed: 150239420

C:\Users\olivier\Downloads>7z e ag10dec18.tar

7-Zip 18.05 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2018-04-30

Scanning the drive for archives:
1 file, 271872000 bytes (260 MiB)

Extracting archive: ag10dec18.tar
--
Path = ag10dec18.tar
Type = tar
Physical Size = 271872000
Headers Size = 551424
Code Page = UTF-8


Would you like to replace the existing file:
  Path:     .\readme.txt
  Size:     649 bytes (1 KiB)
  Modified: 2018-10-24 17:30:49
with the file from archive:
  Path:     agate\libs\readme.txt
  Size:     17 bytes (1 KiB)
  Modified: 2017-07-07 14:01:33
? (Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? Y

ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libogg.so.0
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libogg.so
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libvorbisfile.so
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libm.so.6
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libopenal.so
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libvorbisfile.so.3
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libsndio.so
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libvorbis.so

Would you like to replace the existing file:
  Path:     .\readme.txt
  Size:     17 bytes (1 KiB)
  Modified: 2017-07-07 14:01:33
with the file from archive:
  Path:     agate\libs\gnu\readme.txt
  Size:     293 bytes (1 KiB)
  Modified: 2018-08-19 09:59:35
? (Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? A

ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libSDL2.so
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libSDL2-2.0.so.0
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libcrypto.so
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libSDL2.so
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libopenal.so.1
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libvorbis.so.0
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libvorbisenc.so.2
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libsfml-audio.so.2.5
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libm.so
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libsfml-system.so
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libSDL2-2.0.so.0
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libFLAC.so.8
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libsfml-audio.so
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libFLAC.so
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libsfml-system.so.2.5
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libvorbisenc.so
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libz.so
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\Current
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\vorbis
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\Resources
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\Current
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\SFML
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\Resources
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\Headers
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\Current
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\Resources
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\OpenAL
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libsfml-system.2.5.dylib
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\Current
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\sfml-audio
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\Resources
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libsfml-system.dylib
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\Current
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\FLAC
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\Resources
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\Current
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\Resources
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\vorbisenc
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libsfml-audio.2.5.dylib
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\libsfml-audio.dylib
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\Current
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\vorbisfile
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\Resources
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\freetype
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\Current
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\Resources
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\Current
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\ogg
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\Resources
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\Current
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\sfml-system
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\Resources
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\data
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\adagate_osx
ERROR: Can not create symbolic link : A required privilege is not held by the client. : .\data

Sub items Errors: 63

Archives with Errors: 1

Sub items Errors: 63

C:\Users\olivier\Downloads>

**Comment by fastrgv** [comment]
You may ignore the symbolic link errors because they refer to a subdirectory that is only needed on Mac OSX.  In fact you can delete the subdirectory "adagate.app\" altogether.  BTW, I don't get those messages any more for some reason.  Either because I am an administrator, or because my Windows is up to date.  The symbolic links are actually created on my system.  It's a permission issue.

**Comment by ohenley** [comment]
As-is, all the folders are empty and therefore no executable works (not findings resources probably, relative paths etc...)

IMHO, this should be fixed. The archive should open without errors, and things at proper place. I am perseverant, but most people will just move on.

What is that thing about symbolic link? It links proper resources depending on the platform?

**Comment by fastrgv** [comment]
Are you saying that, for example, the subdirectory .\agate\data\ is empty?
If you have that and .\agate\binw32\adagate32.exe, then I think you have all the resources to run.
BTW, I appreciate your perseverance because I really want to get my stuff to be usable by the average gamer as well as the typical developer.

**Comment by fastrgv** [comment]
This makes it sound as though 7z is the ONLY way...

https://www.simplehelp.net/2015/08/11/how-to-open-tar-gz-files-in-windows-10/

**Comment by fastrgv** [comment]
Ok.  Now we both will have learned something...
if you have windows 10 version 1803 or later, the following windows command extracts a tar.gz file to current directory:
tar -xf NAME.tar.gz

In this case I, once again, get error messages which can all be ignored.
And everything needed for windows compilations and executions works fine!

**Comment by ohenley** [comment]
Good to know. Now, would a zip make life easier an skip any possible problem all together?

**Comment by fastrgv** [comment]
I plan to give that serious consideration.
And let me know if and when you compile everything for yourself.
All my other games & puzzles are setup similarly.

**Comment by fastrgv** [comment]
Conclusions:
1) I plan to distribute zip files in the future, rather than gzipped files.
2) I would like to simply use zip but I found that if I do not tar them up first, the archives are twice as large.

**Comment by TamaMcGlinn** [comment]
```
tama@tardis:~/code/ada/AdaGate$ unzip ~/Downloads/ag6nov20.7z
Archive:  /home/tama/Downloads/ag6nov20.7z
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/tama/Downloads/ag6nov20.7z or
        /home/tama/Downloads/ag6nov20.7z.zip, and cannot find /home/tama/Downloads/ag6nov20.7z.ZIP, period.
```

I fixed this by using `7z e ag6nov20.7z` and then ignoring all errors of this form by saying (A)ll:

```
Would you like to replace the existing file:
  Path:     ./wcmp.bat
  Size:     319 bytes (1 KiB)
  Modified: 2020-11-05 13:32:01
with the file from archive:
  Path:     agate/adabindings/adaOpenAL/adaExample/wcmp.bat
  Size:     331 bytes (1 KiB)
  Modified: 2020-11-05 13:32:01
? (Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit?
```

But then I still end up with an empty src/ directory.

I have never encountered code so difficult to access on github. I assume you have a git repository for the version control on your own work, so why not just upload that directly to github? You could link to it from this AdaGate (or rename this one AdaGate-website to avoid confusion)

**Comment by fastrgv** [comment]
Here is a direct link to the latest version:

https://github.com/fastrgv/AdaGate/releases/download/v7.3.0/ag6nov20.7z

which is clearly a 7Z file. It unzips for me in about 3 seconds on windows
using PeaZip and using the Windows 7z extractor.
On linux it works for me there too (linux Mint), where Nemo seems to know
how to handle a 7z file.
(7z is the only archive type that works on all my delivery outlets, of
which github is merely one of many.)
Let me know if you still have trouble and I'll make a TGZ file for you.
Rod

**Comment by fastrgv** [comment]
ps. I just noticed that I use an alias, and my alias indicates that to
extract a 7z file you type
7z x nameOfFile
so the "e" messes up all the directories!

**Comment by fastrgv** [comment]
PS, any symbolic link errors you might see in Windows refer to files used
ONLY under Mac/OSX and can be disregarded. The system I deliver has
runtimes for OSX, Windows, and Linux...all 3.  The OSX runtime files have a
"mac-bundle" directory structure.

**Comment by fastrgv** [comment]
Sorry, here is a revised statement...the symbolic link errors I see are
related to linux library files that are not needed under Windows. BTW,
those errors would be eliminated with administrator privilege.
